import { useState } from "react";
import { ArrowUpRight, Blocks, Check, Code2, Github, Lightbulb, Linkedin, Mail, Menu, MoveUpRight, Rocket, X } from "lucide-react";
import { SiDocker, SiExpo, SiGit, SiGithub, SiJavascript, SiLinux, SiMongodb, SiNodedotjs, SiNextdotjs, SiPostgresql, SiPython, SiReact, SiTypescript } from "react-icons/si";
import eliasPerfilImg from "@/assets/images/elias-perfil.png";
import { ModeToggle } from "@/components/mode-toggle";

type Lang = "es" | "en";
const copy = {
  es: { nav: ["Sobre mí", "Proyectos", "Experiencia"], eyebrow: "Desarrollador de software", title: "Creo soluciones digitales para problemas reales.", intro: "Soy un desarrollador full-stack que transforma ideas en sitios web, aplicaciones y herramientas útiles para las personas que las necesitan.", work: "Ver mis proyectos", contact: "Hablemos", available: "Abierto a colaborar", selected: "Proyectos seleccionados", selectedIntro: "Una muestra de soluciones en las que he trabajado, desde la idea y la interfaz hasta el código y la puesta en producción.", aboutTitle: "Sobre mí, en pocas palabras.", about: "Soy Elías Ortiz, desarrollador full-stack y aficionado a la tecnología. Me interesa entender los problemas, ordenar lo complejo y convertirlo en software claro, mantenible y agradable de usar.", stack: "Tecnologías que uso", experience: "Mi recorrido", experienceIntro: "Los lugares y equipos que forman parte de mi experiencia como desarrollador.", contactTitle: "¿Trabajamos juntos?", contactIntro: "Si tienes una idea, un proyecto o simplemente quieres conversar sobre tecnología, escríbeme.", name: "Nombre", phone: "Teléfono", message: "Mensaje", send: "Enviar mensaje", sending: "Enviando...", success: "Mensaje enviado. Gracias por escribirme.", error: "No se pudo enviar el mensaje. Inténtalo de nuevo." },
  en: { nav: ["About", "Projects", "Experience"], eyebrow: "Software developer", title: "I create digital solutions for real problems.", intro: "I'm a full-stack developer who turns ideas into websites, applications, and useful tools for the people who need them.", work: "See my projects", contact: "Let's talk", available: "Open to collaboration", selected: "Selected projects", selectedIntro: "A selection of solutions I have worked on, from the idea and interface to the code and production release.", aboutTitle: "About me, in a few words.", about: "I'm Elías Ortiz, a full-stack developer and technology enthusiast. I like understanding problems, bringing order to complexity, and turning it into clear, maintainable, enjoyable software.", stack: "Technologies I use", experience: "My journey", experienceIntro: "The places and teams that have shaped my experience as a developer.", contactTitle: "Shall we work together?", contactIntro: "Have an idea, a project, or simply want to talk about technology? Send me a message.", name: "Name", phone: "Phone", message: "Message", send: "Send message", sending: "Sending...", success: "Message sent. Thanks for reaching out.", error: "Could not send the message. Please try again." },
};

const projects = [
  { title: "Finanz", type: "App web para gestionar gastos personales", tags: ["React", "Firebase", "TypeScript"], href: "https://finanz-services.web.app/auth" },
  { title: "Catlink", type: "Plataforma de e-commerce multitienda", tags: ["React", "TypeScript", "Moda & retail"], href: "https://www.catlink.app/" },
  { title: "Navixsoft", type: "Corporate digital experience", tags: ["React", "TypeScript", "Infrastructure"], href: "https://navixsoft.com" },
];
const technologies = [
  { label: "React", icon: <SiReact />, color: "#61dafb", darkColor: "#61dafb" }, { label: "Expo", icon: <SiExpo />, color: "#111318", darkColor: "#f5f6f8" }, { label: "TypeScript", icon: <SiTypescript />, color: "#3178c6", darkColor: "#69a8ff" },
  { label: "JavaScript", icon: <SiJavascript />, color: "#f0db4f", darkColor: "#f0db4f" }, { label: "Node.js", icon: <SiNodedotjs />, color: "#539e43", darkColor: "#65c85b" }, { label: "Python", icon: <SiPython />, color: "#3776ab", darkColor: "#67b4ff" },
  { label: "Docker", icon: <SiDocker />, color: "#2496ed", darkColor: "#4eb2ff" }, { label: "Linux", icon: <SiLinux />, color: "#111318", darkColor: "#f5f6f8" }, { label: "Git", icon: <SiGit />, color: "#f05032", darkColor: "#ff765c" },
  { label: "GitHub", icon: <SiGithub />, color: "#111318", darkColor: "#f5f6f8" }, { label: "Next.js", icon: <SiNextdotjs />, color: "#111318", darkColor: "#f5f6f8" }, { label: "PostgreSQL", icon: <SiPostgresql />, color: "#4169e1", darkColor: "#6d96ff" },
  { label: "MongoDB", icon: <SiMongodb />, color: "#47a248", darkColor: "#68cf68" }, { label: "shadcn/ui", icon: <Blocks />, color: "#111318", darkColor: "#f5f6f8" },
];
const localizedSections = {
  es: {
    tools: "Tecnologías con las que trabajo", capabilityLabel: "Crear soluciones", capabilityTitle: "Ideas claras, soluciones que funcionan.", capabilityBody: "Me gusta entender el problema antes de construir. Después conecto diseño, código e infraestructura para crear herramientas útiles y fáciles de mantener.", everyPlatform: "Mi forma de trabajar", web: "Frontend", infrastructure: "Backend", delivery: "Deploy", workflowLabel: "Cómo creo soluciones", workflowTitle: "De un problema real a una solución útil.", workflow: [{ title: "Entender", body: "Escucho el problema, hago preguntas y encuentro lo que realmente necesita resolverse." }, { title: "Proponer", body: "Busco una solución simple, explico las decisiones y defino un camino posible." }, { title: "Construir", body: "Escribo código mantenible y avanzo con entregas concretas." }, { title: "Mejorar", body: "Observo cómo funciona, recibo feedback y sigo iterando." }], projectTypes: ["App web para gestionar gastos personales", "Plataforma de e-commerce multitienda de ropa, moda y accesorios", "Experiencia digital corporativa"], experience: [{ year: "2025 — presente", role: "Mid Software Engineer", company: "Navixsoft", desc: "Desarrollo backend y frontend con Python, Node.js, React e infraestructura cloud." }, { year: "2025 — 2026", role: "Desarrollador Full-Stack", company: "Botcamp Roshka", desc: "Creación de interfaces y APIs para productos utilizados por equipos reales." }, { year: "2023 — 2024", role: "Desarrollador Junior", company: "StartUp Factory", desc: "Mantenimiento de sistemas legacy y primeros desarrollos web." }], footer: "Diseñado y construido con cuidado" },
  en: {
    tools: "Technologies I work with", capabilityLabel: "Creating solutions", capabilityTitle: "Clear ideas, solutions that work.", capabilityBody: "I like understanding the problem before building. Then I connect design, code, and infrastructure to create useful, maintainable tools.", everyPlatform: "How I work", web: "Frontend", infrastructure: "Backend", delivery: "Deploy", workflowLabel: "How I create solutions", workflowTitle: "From a real problem to a useful solution.", workflow: [{ title: "Understand", body: "I listen, ask questions, and find what really needs to be solved." }, { title: "Propose", body: "I look for a simple solution, explain the decisions, and define a possible path." }, { title: "Build", body: "I write maintainable code and move forward with concrete deliveries." }, { title: "Improve", body: "I observe how it works, gather feedback, and keep iterating." }], projectTypes: ["Web app for managing personal expenses", "Multi-store e-commerce platform for fashion and accessories", "Corporate digital experience"], experience: [{ year: "2025 — now", role: "Mid Software Engineer", company: "Navixsoft", desc: "Building backend and frontend products with Python, Node.js, React, and cloud infrastructure." }, { year: "2025 — 2026", role: "Full-Stack Developer", company: "Botcamp Roshka", desc: "Creating interfaces and APIs for products used by real teams." }, { year: "2023 — 2024", role: "Junior Developer", company: "StartUp Factory", desc: "Maintaining legacy systems and building web development foundations." }], footer: "Designed and built with care" },
};

export default function Home() {
  const [lang, setLang] = useState<Lang>("es");
  const [menuOpen, setMenuOpen] = useState(false);
  const [formData, setFormData] = useState({ name: "", phone: "", message: "" });
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle");
  const [submitting, setSubmitting] = useState(false);
  const t = copy[lang];
  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault(); setSubmitting(true); setStatus("idle");
    try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(formData) }); if (!response.ok) throw new Error("Request failed"); setStatus("success"); setFormData({ name: "", phone: "", message: "" }); } catch { setStatus("error"); } finally { setSubmitting(false); }
  };
  return (
    <main className="expo-page">
      <header className="expo-nav"><a className="expo-brand" href="#top" aria-label="Elías Ortiz home">Elías Ortiz</a><nav className={menuOpen ? "expo-links is-open" : "expo-links"}><a href="#about">{t.nav[0]}</a><a href="#projects">{t.nav[1]}</a><a href="#experience">{t.nav[2]}</a></nav><div className="expo-nav-actions"><button className="lang-button" onClick={() => setLang(lang === "es" ? "en" : "es")} aria-label="Change language">{lang.toUpperCase()}</button><ModeToggle /><a className="dashboard-button" href="#contact">{t.contact} <ArrowUpRight size={14} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></div></header>
      <section className="expo-hero hero-only" id="top"><div className="hero-copy"><div className="eyebrow">{t.available}</div><p className="hero-kicker">{t.eyebrow}</p><h1>{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="primary-button" href="#projects">{t.work} <MoveUpRight size={17} /></a><a className="text-button" href="#contact">{t.contact} <ArrowUpRight size={16} /></a></div></div></section>
      <section className="trust-strip"><span className="trust-title">{localizedSections[lang].tools}</span><div className="brand-window"><div className="brand-rail">{[...technologies, ...technologies].map((technology, index) => <span className="brand-tile" key={`${technology.label}-${index}`} title={technology.label} style={{ "--brand-color": technology.color, "--brand-dark-color": technology.darkColor } as React.CSSProperties}>{technology.icon}</span>)}</div></div></section>
      <section className="capability-section"><div className="capability-copy"><span className="section-label">{localizedSections[lang].capabilityLabel}</span><h2>{localizedSections[lang].capabilityTitle}</h2><p>{localizedSections[lang].capabilityBody}</p></div><div className="platform-card"><div className="platform-badge"><SiReact /> <span>+</span> <Code2 /></div><div className="platform-panel"><div className="platform-heading"><span className="device-icon">◫</span><strong>{localizedSections[lang].everyPlatform}</strong><span className="toggle active" /></div><div className="platform-row"><span><SiLinux /> {localizedSections[lang].web}</span><span className="toggle active" /></div><div className="platform-row"><span><SiDocker /> {localizedSections[lang].infrastructure}</span><span className="toggle active" /></div><div className="platform-row"><span><SiGithub /> {localizedSections[lang].delivery}</span><span className="toggle active" /></div></div></div></section>
      <section className="workflow-section"><div className="workflow-heading"><span className="section-label">{localizedSections[lang].workflowLabel}</span><h2>{localizedSections[lang].workflowTitle}</h2></div><div className="workflow-grid">{localizedSections[lang].workflow.map((step, index) => { const icons = [Lightbulb, Blocks, Code2, Rocket]; const Icon = icons[index]; return <article className="workflow-step" key={step.title}><span className="workflow-number">0{index + 1}</span><Icon size={23} strokeWidth={1.7} /><h3>{step.title}</h3><p>{step.body}</p></article>; })}</div></section>
      <section className="project-gallery" id="projects"><div className="gallery-heading"><span className="gallery-label">01 / {t.selected}</span><h2>{lang === "es" ? "Lo que construyo" : "What I build"}</h2><p>{t.selectedIntro}</p></div><div className="gallery-track">{projects.map((project, index) => <article className={`gallery-card gallery-card-${index + 1}`} key={project.title}><a className="gallery-preview" href={project.href} target="_blank" rel="noreferrer"><div className="browser-chrome"><span /><span /><span /><small>{project.title.toLowerCase()}.app</small></div><iframe src={project.href} title={`${project.title} preview`} loading="lazy" tabIndex={-1} /><span className="gallery-shade" /><span className="gallery-open"><ArrowUpRight size={18} /></span></a><div className="gallery-info"><div><h3>{project.title}</h3><p>{localizedSections[lang].projectTypes[index]}</p></div><div className="gallery-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="expo-section about-section" id="about"><div className="about-index section-label">02 / {t.aboutTitle}</div><div className="about-content"><div className="about-intro"><div className="about-photo"><img src={eliasPerfilImg} alt="Elías Ortiz" /></div><div><h2>{t.aboutTitle}</h2><p>{t.about}</p></div></div><div className="stack-row"><span className="section-label">{t.stack}</span><div className="tech-list">{technologies.map((technology) => <span key={technology.label} style={{ "--brand-color": technology.color, "--brand-dark-color": technology.darkColor } as React.CSSProperties}>{technology.icon}{technology.label}</span>)}</div></div></div></section>
      <section className="expo-section experience-section" id="experience"><div className="section-heading"><div><span className="section-label">03 / {t.experience}</span><h2>{t.experience}</h2></div><p>{t.experienceIntro}</p></div><div className="experience-list">{localizedSections[lang].experience.map((item) => <div className="experience-item" key={item.company}><span className="experience-year">{item.year}</span><div><h3>{item.role}</h3><strong>{item.company}</strong><p>{item.desc}</p></div><Check className="experience-check" size={18} /></div>)}</div></section>
      <section className="contact-section" id="contact"><div><span className="section-label">04 / {t.contact}</span><h2>{t.contactTitle}</h2><p>{t.contactIntro}</p><div className="social-links"><a href="https://github.com/esam-dev" target="_blank" rel="noreferrer"><Github size={18} /> GitHub</a><a href="https://www.linkedin.com/in/el%C3%ADas-ort%C3%ADz-a5895224b/" target="_blank" rel="noreferrer"><Linkedin size={18} /> LinkedIn</a><a href="mailto:emails.eliasortiz@gmail.com"><Mail size={18} /> Email</a></div></div><form className="contact-form" onSubmit={handleSubmit}><label>{t.name}<input required name="name" value={formData.name} onChange={(event) => setFormData({ ...formData, name: event.target.value })} /></label><label>{t.phone}<input required name="phone" type="tel" value={formData.phone} onChange={(event) => setFormData({ ...formData, phone: event.target.value })} /></label><label>{t.message}<textarea required name="message" rows={4} value={formData.message} onChange={(event) => setFormData({ ...formData, message: event.target.value })} /></label><button className="primary-button" disabled={submitting}>{submitting ? t.sending : t.send} <ArrowUpRight size={17} /></button>{status === "success" && <p className="form-status success">{t.success}</p>}{status === "error" && <p className="form-status error">{t.error}</p>}</form></section>
      <footer className="expo-footer"><span>© 2026 Elías Ortiz</span><span>{localizedSections[lang].footer}</span><a href="#top">{lang === "es" ? "Volver arriba ↑" : "Back to top ↑"}</a></footer>
    </main>
  );
}